_BASE_: "../COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"
OUTPUT_DIR: /nfs/andrew/mrcnn/logs/latent_polybag
MODEL:
  META_ARCHITECTURE: "LatentRCNN"
DATASETS:
  TRAIN:
    - polybag_train
  TEST:
    - polybag_val
INPUT:
  MASK_FORMAT: bitmask
