_BASE_: "../COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
OUTPUT_DIR: /nfs/andrew/mrcnn/logs/latent_mrcnn_coco_learned_prior
MODEL:
  META_ARCHITECTURE: "LatentRCNN"
  KL:
    LEARNED_PRIOR: True
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
