_BASE_: "../COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"
OUTPUT_DIR: /nfs/andrew/mrcnn/logs/latent_polybag_coco_learned_prior
MODEL:
  META_ARCHITECTURE: "LatentRCNN"
  WEIGHTS: /nfs/andrew/mrcnn/logs/latent_polybag_coco_learned_prior/2021-05-17-22-28-20/model_final.pth
  KL:
    LEARNED_PRIOR: True
    CONST_SCALE: 1e-5
    LOSS: True
DATASETS:
  TRAIN:
    - polybag_train
  TEST:
    - polybag_val
INPUT:
  MASK_FORMAT: bitmask
SOLVER:
  BASE_LR: 0.0002
  STEPS: (29999,)
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 2000
