_BASE_: "../COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"
OUTPUT_DIR: /nfs/andrew/mrcnn/logs/latent_toy
MODEL:
  META_ARCHITECTURE: "LatentRCNN"
  KL:
    CONST_SCALE: 0.1
    LOSS: False
DATASETS:
  TRAIN:
    - uncertainty_train
  TEST:
    - uncertainty_train
INPUT:
  MASK_FORMAT: bitmask
  MIN_SIZE_TRAIN: (800, )
  RANDOM_FLIP: horizontal
SOLVER:
  BASE_LR: 0.02
  STEPS: (5000, 7000)
  MAX_ITER: 9000
AGREEMENT:
  THRESHOLD: 0.9
  NSAMPLES: 16
  AUGMENTATIONS: ["none"]
  MIN_AREA: 100