_BASE_: "../COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"
OUTPUT_DIR: /nfs/andrew/mrcnn/logs/latent_mrcnn_coco
MODEL:
  META_ARCHITECTURE: "LatentRCNN"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
