_BASE_: "../COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"
OUTPUT_DIR: /nfs/nikhil/logs/detectron2/mrcnn_polybag_from_coco
MODEL:
  WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
DATASETS:
  TRAIN:
    - polybag_train
  TEST:
    - polybag_val
INPUT:
  MASK_FORMAT: bitmask
