_BASE_: "../COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"
OUTPUT_DIR: /nfs/andrew/mrcnn/logs/mrcnn_toy
DATASETS:
  TRAIN:
    - uncertainty_train
  TEST:
    - uncertainty_train
INPUT:
  MIN_SIZE_TRAIN: (800, )
  RANDOM_FLIP: horizontal
SOLVER:
  BASE_LR: 0.02
  STEPS: (5000, 7000)
  MAX_ITER: 9000
