_BASE_: "../COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"
OUTPUT_DIR: /nfs/nikhil/logs/detectron2/mrcnn_polybag
DATASETS:
  TRAIN:
    - polybag_train
  TEST:
    - polybag_val
INPUT:
  MASK_FORMAT: bitmask
